### ISSUE TITLE
Breadcrumb Light Link Default - Missing

### ISSUE THREAD

**Issue by roarytubbs** [predixdesignsystem/predix-design-stencil#1]
It seems there is a missing item for the Light Breadcrumb. I have attached a screenshot. 

![screen shot 2018-01-11 at 3 11 39 pm](https://user-images.githubusercontent.com/1294345/34847675-c670eea4-f6e1-11e7-81d4-8c9bf75c3ed2.jpg)

**Comment by waifong** [comment]
@roarytubbs I can't seem to reproduce this on my end. Is the issue happening when you try to insert the symbol? Which version of Sketch are you using?

**Comment by roarytubbs** [comment]
@waifong 
It happens when I change the sate. Now that I look closer at this it seems there are two "default" states being pulled in. I did a git pull to ensure I have the latest and I'm using Sketch 48.2. 
![missing-symbol](https://user-images.githubusercontent.com/1294345/35050296-13b9888a-fb68-11e7-9d69-518dad6cc0f4.gif)

**Comment by waifong** [comment]
@roarytubbs Got it. It looks like the states share a dimension with the parent. Usually that doesn't cause a problem, but it seems to have created an empty override from it. It's an easy fix. I will push an update to fix this issue after our walkthrough session today. The correct default state is the first option in the list.

**Comment by waifong** [comment]
@roarytubbs Fixed the breadcrumb issue. Feel free to fetch the latest version of the Master to get the fix.
