### ISSUE TITLE
Tabs selected state spacing is off

### ISSUE THREAD

**Issue by arcpato** [predixdesignsystem/predix-design-stencil#10]
The vertical spacing on the selected state of tabs is a lot taller than the default and disabled states, making the comps jumpy.

![screen shot 2018-03-14 at 4 19 31 pm](https://user-images.githubusercontent.com/6137443/37436139-b0d736dc-27a3-11e8-85b3-46dd6a183802.png)

**Comment by waifong** [comment]
I can't seem to reproduce this issue. When you insert the symbol, it displays higher or does it occur when you switch the override?

**Comment by arcpato** [comment]
Both. When placing the symbol I get this. (Tab light and dark)
![screen shot 2018-03-16 at 2 51 51 pm](https://user-images.githubusercontent.com/6137443/37546392-cf9e38a4-2929-11e8-9811-1f40427a5ef1.png)

And when i copy that one and place next to it, and change the state it jumps.
![screen shot 2018-03-16 at 2 52 19 pm](https://user-images.githubusercontent.com/6137443/37546387-cbc4c950-2929-11e8-94a0-7978820e0551.png)

**Comment by waifong** [comment]
I can't seem to reproduce from my end so I created a new instance of the tabs. Can you fetch the latest and see if it fixes the issue. Thanks

**Comment by arcpato** [comment]
yup, that worked. 
![screen shot 2018-03-30 at 4 05 57 pm](https://user-images.githubusercontent.com/6137443/38156629-4501c13c-3434-11e8-80bc-d6ad82e3bab0.png)
