### ISSUE TITLE
Request for cursor disabled/blocked state

### ISSUE THREAD

**Issue by arcpato** [predixdesignsystem/predix-design-stencil#14]
Request to include the disabled cursor state as part of the cursor symbols. A disabled state will help illustrate disabled interactions.

![screen shot 2018-03-30 at 4 08 26 pm](https://user-images.githubusercontent.com/6137443/38156691-bd377f5c-3434-11e8-8762-e6c889da0ab4.png)

**Comment by waifong** [comment]
A disabled state has been added to the cursor symbol. Available in the latest Library update
