### ISSUE TITLE
Table Example with Checkboxes does not include "Select All" checkbox at the top

### ISSUE THREAD

**Issue by agmilmoe** [predixdesignsystem/predix-design-stencil#15]
It's not clear how a user would select all in the (Group 11) example in the Sketch template.

There is no checkbox in the header, and I would assume clicking SELECTED would sort.

**Comment by arcpato** [comment]
Will fix this in the next update

![screen shot 2019-01-10 at 1 56 28 pm](https://user-images.githubusercontent.com/6137443/51000571-68819d00-14e2-11e9-8b83-ef145010c8d4.png)

**Comment by arcpato** [comment]
Just pushed an update that addresses this.
