### ISSUE TITLE
Request for basic label

### ISSUE THREAD

**Issue by arcpato** [predixdesignsystem/predix-design-stencil#16]
I find myself using labels for forms that involve other types of data entry mechanism like dropdowns.

Currently the label symbol only appears with the form field. Could you add the Label symbol by itself as an option without the form field?

Example usage:
![screen shot 2018-05-02 at 12 36 37 pm](https://user-images.githubusercontent.com/6137443/39545258-7b841e9a-4e05-11e8-99f0-51b634e72b85.png)

**Comment by waifong** [comment]
Form label has been added to the latest version of the library. It is now available to download
