### ISSUE TITLE
GE Inspira Sans

### ISSUE THREAD

**Issue by what-the-hex** [predixdesignsystem/predix-design-stencil#18]
I'm trying to use the Design Starter Kit but it doesn't seem to come with GE Inspira Sans font. There's a copy of SF from Apple but all the symbols are created with GE Inspira.

![screen shot 2019-01-21 at 2 39 21 pm](https://user-images.githubusercontent.com/46908114/51502313-5cbb9380-1d8a-11e9-8229-f849bc9c2ac9.png)

**Comment by evanjd** [comment]
@arcpato Is there a reason why we don't distribute GE Inspira Sans with the design stencil?

@what-the-hex For now you can grab the fonts from [px-typography-design](https://github.com/predixdesignsystem/px-typography-design/tree/master/type).

**Comment by what-the-hex** [comment]
Thanks, I actually grabbed those earlier and was not able to get them to work for the symbols in Sketch. While the font works in Sketch the symbols are still not recognizing the font or letting me update these styles.

**Comment by arcpato** [comment]
Most folks already had the fonts installed from the GE Internal Brand site, so I can only assume that is why it was never part of the package.

I can add the fonts in here for the next update though.

**Comment by arcpato** [comment]
Just pushed an update that includes the fonts.
