### ISSUE TITLE
Chip right border disappears on larger chips

### ISSUE THREAD

**Issue by arcpato** [predixdesignsystem/predix-design-stencil#3]
Chip right border does not show up when you have large text within, and expand the chip to fit within the right padding. 

Example of max width that works:
![screen shot 2018-01-26 at 10 31 16 am](https://user-images.githubusercontent.com/6137443/35456468-658b01c4-028a-11e8-9a6a-392b393a5b0c.png)

Example where it does NOT work:
![screen shot 2018-01-26 at 10 31 01 am](https://user-images.githubusercontent.com/6137443/35456473-6c756efc-028a-11e8-9f1d-582e1d2cf896.png)

**Comment by waifong** [comment]
Looks like the edge of the chip was hanging off the canvas by a pixel. Bumped it in a pixel. Should be fixed now. Fetching the latest will fix it.
