### ISSUE TITLE
Additional colors for icons

### ISSUE THREAD

**Issue by roarytubbs** [predixdesignsystem/predix-design-stencil#4]
Can the status colors be added to the icon overlay colors? It would be great to be able to use a trending up/down arrow with the proper colors. Right now it's limited.
![screen shot 2018-01-31 at 10 34 17 am](https://user-images.githubusercontent.com/1294345/35634862-553630a0-0672-11e8-849f-18065ff64241.jpg)

**Comment by waifong** [comment]
I will look into adding color categories for the icons. Good suggestion.

**Comment by arcpato** [comment]
Added the status colors for icons.
