### ISSUE TITLE
Add a symbol for the brand bar when collapsed

### ISSUE THREAD

**Issue by agmilmoe** [predixdesignsystem/predix-design-stencil#6]
Ideally tied to the same color, so that if we modify the brand bar color for a customer it changes in both the brand bar and the collapsed brand bar.

Thanks!

**Comment by waifong** [comment]
A scrolled state is already in the symbol. You can find it in the State override. If you are building a custom branding bar, you can detach the symbol and use the predix version as a base to customize for your needs.

**Comment by agmilmoe** [comment]
Oh, cool. I was just looking in the components examples.

Thanks!
