### ISSUE TITLE
Request for label symbol

### ISSUE THREAD

**Issue by arcpato** [predixdesignsystem/predix-design-stencil#7]
As part of the forms items, a good addition would be a simple label, with no value or value field associated.

I have used this often to create forms with dropdowns as an example. 

![screen shot 2018-03-08 at 5 45 02 pm](https://user-images.githubusercontent.com/6137443/37186108-9146357a-22f8-11e8-9ed5-bdc22f61375f.png)

![screen shot 2018-03-08 at 5 43 13 pm](https://user-images.githubusercontent.com/6137443/37186113-9623c242-22f8-11e8-87a0-1b5a967e8389.png)

The symbol exists as you use it as part of the form symbols, so it is a matter of exposing the label by itself :)

**Comment by waifong** [comment]
That's a great suggestion. We've got others who have requested this as well. It's been added to the Library. Fetch the latest version and you can find it in the Forms category as Form Label
