### ISSUE TITLE
Search Field Into symbols request

### ISSUE THREAD

**Issue by arcpato** [predixdesignsystem/predix-design-stencil#8]
Request to add a symbol for a search field, and an advanced search

![screen shot 2018-03-09 at 3 42 36 pm](https://user-images.githubusercontent.com/6137443/37235072-8a0e88bc-23b0-11e8-8c77-7f85ebd1014d.png)

**Comment by waifong** [comment]
A search field (type ahead) has been added to the latest version of the library file.
