### ISSUE TITLE
Request for scroll bar

### ISSUE THREAD

**Issue by arcpato** [predixdesignsystem/predix-design-stencil#9]
Request to add a scroll bar symbol for wireframe purposes only

![screen shot 2018-03-09 at 3 43 45 pm](https://user-images.githubusercontent.com/6137443/37235110-d29261d0-23b0-11e8-97c2-23bbcc9f9bde.png)

**Comment by waifong** [comment]
Scrollbars are available in the latest update of the library file. Multiple browser styles are available.
